# Generated by Django 2.0.5 on 2018-07-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nkjob', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gif_init',
            new_name='position_51',
        ),
    ]
