# Generated by Django 2.0.5 on 2018-07-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkjob', '0002_auto_20180713_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position_51',
            name='addr',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='position_51',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='position_51',
            name='pay',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='position_51',
            name='position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='position_51',
            name='up_time',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='position_51',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
